name: xronos-dashboard

include:
  - ../../docker-compose.yml

services:
  deadline-misses-c:
    pull_policy: missing
    build:
      context: ./c/src-gen/DeadlineMisses/
    container_name: deadline-misses-c
    hostname: deadline-misses-c
    networks:
      - xronos-dashboard
    links:
      - telegraf
    environment:
      LF_TELEGRAF_HOST_NAME: ${LF_TELEGRAF_HOST_NAME:-host.docker.internal}
    stop_signal: SIGINT
    depends_on:
      telegraf:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true
