{
 "title": "LF Tracing",
 "description": "A collection of Grafana panels to monitor a federated LF application",
 "time": { "from": "now - 15s", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Processes online",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 8 }
   ]
  },
  {
   "title": "Time since last activity",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "import \"join\"\nimport \"system\"\nimport \"array\"\nimport \"internal/debug\"\n\nheartbeats = from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => (r[\"_measurement\"] == \"FederateNames\" and r[\"_field\"] == \"other_process_name\"))\n  |> rename(columns: {\"_value\": \"other_process_name\"})\n  |> group()\n  |> keep(columns: [\"other_process_name\", \"_time\", \"process_name\"])\n\nlatest_tracepoints = from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => (r[\"_measurement\"] == \"TraceRecord\" and r[\"_field\"] == \"process_id\"))\n  |> rename(columns: {\"_value\": \"process_id\"})\n  |> keep(columns: [\"process_id\", \"_time\", \"process_name\"])\n  |> group(columns: [\"process_id\"]) |> max(column: \"_time\") |> group()\n\nisEmpty = (tables) => {\n\tcolumnsArray = tables\n\t\t|> columns()\n\t\t|> findColumn(fn: (key) => true, column: \"_value\")\n\treturn length(arr: columnsArray) == 0\n}\n\nd = join.left(\n  left: heartbeats |> keep(columns: [\"other_process_name\"]) |> unique(column: \"other_process_name\"),\n  right: if isEmpty(tables: latest_tracepoints)\n    then array.from(rows: [{\n      process_id: debug.null(type: \"int\"),\n      _time: time(v: 0),\n      process_name: debug.null(type: \"string\")}])\n    else latest_tracepoints,\n  on: (l, r) => l.other_process_name == r.process_name,\n  as: (l, r) => ({l with\n    other_time: r._time\n  }))\n  |> group(columns: [\"other_process_name\"])\n  |> map(fn: (r) => ({r with other_time: if exists r.other_time then r.other_time else time(v: 0)}))\n  |> max(column: \"other_time\")\n  |> group()\ne = join.left(\n  left: d, right: heartbeats,\n  on: (l, r) => l.other_process_name == r.process_name,\n  as: (l, r) => (if not exists l.other_time or r._time > l.other_time\n    then (if not exists r._time then {l with greater_time: time(v: 0), last_message: \"NONE\"} else {l with greater_time: r._time, last_message: \"HEARTBEAT\"})\n    else {l with greater_time: l.other_time, last_message: \"TRACEPOINT\"})\n  )\n  |> keep(columns: [\"greater_time\", \"other_process_name\", \"last_message\"])\n  |> group(columns: [\"other_process_name\"])\n  |> max(column: \"greater_time\")\n  |> group()\n  |> map(fn: (r) => ({r with time_since_last_activity:\n    if r.greater_time == time(v: 0)\n     then debug.null(type: \"time\")\n     else (int(v: system.time()) - int(v: r.greater_time))}))\n\nret = e\n  |> drop(columns: [\"greater_time\"])\n  |> map(fn: (r) => ({r with status: if not exists r.time_since_last_activity\n    then \"DISCONNECTED\"\n    else (if r.last_message == \"TRACEPOINT\" then \"OK\" else \"QUIET\")}))\n  |> drop(columns: [\"last_message\"])\n  |> rename(columns: {\n    \"other_process_name\": \"Process\",\n    \"time_since_last_activity\": \"Age of latest data\"\n    })\nret"
    }
   ]
  },
  {
   "title": "Invocations by reactor",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TraceRecord\")\n  |> filter(fn: (r) => r[\"_field\"] == \"process_id\")\n  |> filter(fn: (r) => exists r.id_description and not strings.hasPrefix(prefix: \"nr_\", v: r.id_description) and not strings.hasPrefix(prefix: \"ns_\", v: r.id_description))\n  |> filter(fn: (r) => r[\"event_kind_description\"] == \"Reaction starts\")\n  |> group()\n  |> drop(columns: [\"host\", \"worker\", \"dst_id\", \"src_id\", \"_field\", \"_time\", \"process_name\", \"_measurement\"])\n  |> group(columns: [\"id_description\"])\n  |> count()\n  |> group()\n  |> sort(desc: true)\n  |> rename(columns: {id_description: \"Reactor\", _value: \"Number of reaction executions\"})"
    }
   ]
  },
  {
   "title": "Processes disconnected",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 8 }
   ]
  },
  {
   "title": "Maximum lag per reactor over logical time",
   "type": "timeseries",
   "description": "The x-axis is the logical time, and the y-axis is the maximum lag (physical time minus logical time) observed in a given reactor at a logical time.",
   "gridPos": { "h": 17, "w": 15, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "import \"strings\"\n\nungrouped = from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TraceRecord\")\n  |> filter(fn: (r) => r[\"_field\"] == \"logical_time\")\n  |> filter(fn: (r) => r[\"network_reactor\"] == \"false\")\n  |> filter(fn: (r) => r.event_kind_description == \"Reaction starts\")\n  |> keep(columns: [\"event_kind_description\", \"id_description\", \"process_name\", \"_time\", \"_value\", \"\"])\n  |> group(columns: [\"id_description\", \"_value\"])\n  |> map(fn: (r) => ({r with \"lag in\": int(v: r._time) - int(v: r._value)}))\n  |> max(column: \"lag in\")\n\nret = ungrouped\n  |> keep(columns: [\"_value\", \"lag in\", \"process_name\", \"id_description\"])\n  |> map(fn: (r) => ({r with _value: time(v: r._value)}))\n  |> rename(columns: {_value: \"_time\"})\n  |> group(columns: [\"id_description\"])\n  |> filter(fn: (r) => exists r.id_description)\n\nret"
    }
   ]
  },
  {
   "title": "Max lag (nanoseconds) in the current time interval",
   "type": "bargauge",
   "description": "This is the maximum lag (difference between physical and logical time) at the start of any reaction execution in the current time interval.",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TraceRecord\")\n  |> filter(fn: (r) => r[\"_field\"] == \"lag\")\n  |> keep(columns: [\"process_name\", \"_value\"])\n  |> group(columns: [\"process_name\"])\n  |> max()\n  |> rename(columns: {_value: \"lag in \"})"
    }
   ]
  },
  {
   "title": "Reaction WCET",
   "type": "barchart",
   "description": "This is the maximum observed execution time for each reaction that was executed in the current time interval. It does not rule out the possibility that reactions might take longer in the future.",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"math\"\n\nreactions = from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TraceRecord\")\n  |> filter(fn: (r) => r.network_reactor == \"false\")\n  |> filter(fn: (r) => r[\"_field\"] == \"logical_time\")\n  |> filter(fn: (r) => r.event_kind_description == \"Reaction starts\" or r.event_kind_description == \"Reaction ends\")\n  |> map(fn: (r) => ({ r with reaction_id: \"${r[\"id_description\"]} reaction ${r[\"dst_id\"]}\"}))\n  |> group(columns: [\"reaction_id\"])\n  |> pivot(\n    rowKey: [\"_value\"],\n    columnKey: [\"event_kind_description\"],\n    valueColumn: \"_time\"\n  )\n  |> map(fn: (r) => ({ r with _value: uint(v: r[\"Reaction ends\"]) - uint(v: r[\"Reaction starts\"]) }))\n  |> drop(columns: [\"Reaction starts\", \"Reaction ends\"])\n  |> max()\n  |> group()\n  |> sort(columns: [\"reaction_id\"])\n  \nreactions"
    }
   ]
  },
  {
   "title": "Reaction executions (red indicates deadline violation)",
   "type": "state-timeline",
   "description": "Position on the timeline corresponds to physical time.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"math\"\nimport \"internal/debug\"\n\nreactions = from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TraceRecord\")\n  |> filter(fn: (r) => r.network_reactor == \"false\")\n  |> filter(fn: (r) => r[\"_field\"] == \"logical_time\")\n  |> filter(fn: (r) => r.event_kind_description == \"Reaction starts\" or r.event_kind_description == \"Reaction ends\")\n  |> group(columns: [\"id_description\"])\n  |> keep(columns: [\"_time\", \"_value\", \"event_kind_description\", \"id_description\", \"extra_delay\"])\n  |> sort(columns: [\"_time\"])\n  |> map(fn: (r) => ({r with \"extra_delay\": int(v: r.extra_delay)}))\n  |> map(fn: (r) => ({r with \"event\": if r.event_kind_description == \"Reaction ends\" then \"IDLE\" else (if int(v: r._time) > r._value + r.extra_delay and r.extra_delay > 0 then \"DEADLINE_VIOLATED\" else \"EXECUTING\")}))\n  |> group()\n  |> drop(columns: [\"_value\"])\n\n\nfinal_values = reactions\n|> group(columns: [\"id_description\"])\n|> sort(columns: [\"_time\"])\n|> last(column: \"_time\")\n|> group()\n|> map(fn: (r) => ({r with \"_time\": v.timeRangeStop}))\n\nret = union(tables: [reactions, final_values])\n  |> map(fn: (r) => ({r with \"id_description2\": r.id_description}))\n  |> pivot(\n    rowKey: [\"_time\", \"id_description2\"],\n    columnKey: [\"id_description\"],\n    valueColumn: \"event\"\n  )\n  |> drop(columns: [\"id_description2\"])\n\nret"
    }
   ]
  },
  {
   "title": "Reaction executions (opacity indicates logical time and microstep)",
   "type": "state-timeline",
   "description": "Areas with a higher opacity correspond to reaction executions that have later logical tags (where a tag is a logical time combined with a microstep). Position on the timeline corresponds to physical time.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"math\"\nimport \"internal/debug\"\nimport \"join\"\n\nmicrosteps = from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TraceRecord\")\n  |> filter(fn: (r) => r.network_reactor == \"false\")\n  |> filter(fn: (r) => r[\"_field\"] == \"microstep\")\n  |> filter(fn: (r) => r.event_kind_description == \"Reaction starts\" or r.event_kind_description == \"Reaction ends\")\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> group()\n\nbefore_difference = from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TraceRecord\")\n  |> filter(fn: (r) => r.network_reactor == \"false\")\n  |> filter(fn: (r) => r[\"_field\"] == \"logical_time\")\n  |> filter(fn: (r) => r.event_kind_description == \"Reaction starts\" or r.event_kind_description == \"Reaction ends\")\n  |> group(columns: [\"id_description\"])\n  |> keep(columns: [\"_time\", \"_value\", \"event_kind_description\", \"id_description\"])\n  |> group()\n  |> map(fn: (r) => ({r with \"event\": r._value}))\n  |> sort(columns: [\"_value\", \"_time\"])\n\n\n// initial_value = set_priority |> first(column: \"extra_delay\") |> map(fn: (r) => ({r with \"_time\": v.timeRangeStart}))\n\n// union(tables: [initial_value, set_priority])\n\ninitial_value = before_difference |> first(column: \"_value\")\n\njoined = join.inner(\n  left: union(tables: [initial_value, before_difference]),\n  right: microsteps,\n  on: (l, r) => l._time == r._time,\n  as: (l, r) => ({l with microstep: r._value})\n)\n\nreactions = joined\n  |> sort(columns: [\"_value\", \"_time\"])\n  |> difference(columns: [\"event\", \"microstep\"])\n  |> map(fn: (r) => ({r with \"event\": if r.event > 0 or r.microstep > 0 then 1 else 0}))\n  |> cumulativeSum(columns: [\"event\"])\n  |> sort(columns: [\"id_description\", \"_time\"])\n  |> map(fn: (r) => ({r with \"event\": if r.event_kind_description == \"Reaction ends\" then -1 else r.event}))\n  |> drop(columns: [\"_value\", \"event_kind_description\"])\n\nfinal_values = reactions\n  |> group(columns: [\"id_description\"])\n  |> sort(columns: [\"_time\"])\n  |> last(column: \"_time\")\n  |> group()\n  |> map(fn: (r) => ({r with \"_time\": v.timeRangeStop}))\n\nret = union(tables: [reactions, final_values])\n  |> map(fn: (r) => ({r with \"id_description2\": r.id_description}))\n  |> pivot(\n    rowKey: [\"_time\", \"id_description2\"],\n    columnKey: [\"id_description\"],\n    valueColumn: \"event\"\n  )\n  |> drop(columns: [\"id_description2\"])\n\nret"
    }
   ]
  },
  {
   "title": "Deadline violations per scheduled reaction",
   "type": "barchart",
   "description": "Reactions without deadlines are excluded from this calculation.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"math\"\nimport \"internal/debug\"\n\nreactions = from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TraceRecord\")\n  |> filter(fn: (r) => r.network_reactor == \"false\")\n  |> filter(fn: (r) => r[\"_field\"] == \"logical_time\")\n  |> filter(fn: (r) => r.event_kind_description == \"Reaction starts\")\n  |> group(columns: [\"id_description\"])\n  |> keep(columns: [\"_time\", \"_value\", \"id_description\", \"extra_delay\"])\n  |> map(fn: (r) => ({r with \"extra_delay\": int(v: r.extra_delay)}))\n  |> map(fn: (r) => ({r with \"Deadline violations per scheduled reaction\": if r.extra_delay < 0 then debug.null(type: \"int\") else if int(v: r._time) > r._value + r.extra_delay then 1 else 0}))\n  |> drop(columns: [\"extra_delay\", \"_value\"])\n  |> mean(column: \"Deadline violations per scheduled reaction\")\n  |> group()\n  |> filter(fn: (r) => exists r[\"Deadline violations per scheduled reaction\"])\nreactions"
    }
   ]
  }
 ]
}