name: CI

on:
  push:
    branches:
      - main
      - ci-test

jobs:
  e2e-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '21'

      - name: Install Lingua Franca
        run: |
          curl -Ls https://install.lf-lang.org | bash -s cli

      - name: Build the Test Publisher
        run: |
          (cd InfluxPublisher && bash run_build.sh)

      - name: Start Test Publisher environment
        run: |
          (cd InfluxPublisher && docker compose up -d --build)

      - name: Install jq
        run: |
          sudo apt-get install -y jq

      - name: Run E2E Tests
        run: |
          (cd InfluxPublisher/tests && bash test_publisher_e2e.sh)

      - name: Tear down Docker containers
        run: |
          docker compose -f docker-compose.yml down
          docker compose -f ./InfluxPublisher/docker-compose.yml down

      - name: Reject Merge (Tests Failed)
        if: failure()
        run: |
          echo "docker compose version" $(docker compose --version)
          exit 1
